name: Nexxo CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Lint & Format
      run: npm run lint

    - name: Build Core
      run: npm run build

    - name: Run Unit Tests
      run: npx tsx src/test/runner.ts

    - name: Run Determinism Check
      run: npx tsx src/test/determinism.ts

    - name: Run E2E Security Check
      run: npx tsx src/test/runner.ts tests/e2e/security.test.ts
